<div class="main-conatainer">
    <div class="main-widgets">
        <!-- each block is dynamicaly populated by js script -->
        <div class="block widget"></div>
        <div class="block widget"></div>
        <div class="block widget"></div>
        <div class="block widget"></div>
    </div>
    <div class="main-statistic">
        <div class="block statistics">
            <canvas id="curveTotalByMonth"></canvas>
            <div class="total">
                <h2 class="total-title">Tendance du solde:</h2>
                <a href="statistique" class="total-subcontainer">
                    <span class="total-subtitle">Total aujourd'hui:</span>
                    <span class="total-amount"></span>
                </a>
            </div>
        </div>
        <div class="block accounts">
            <!-- list of accounts is dynamicaly generated by js script -->
        </div>
    </div>
    <div class="main-operations">
        <div class="block operations">
            <div class="operations-title">
            </div>
            <ul class="operation-list">
                <!-- list of operations is dynamicaly generated by js script -->
            </ul>
        </div>
    </div>
</div>
<div id="overlay" class="overlay hidden"></div>
<script>
    // Retrieve the selected account ID passed from PHP and parse it to an integer
    const selectedAccount = +JSON.parse('<?php echo $selectedAccountJSON; ?>');
    // Retrieve and parse the accounts in JSON format passed from PHP
    const accountsJSON = JSON.parse('<?php echo $accountsJSON; ?>');
    // Retrieve and parse the categories in JSON format passed from PHP
    const categories = JSON.parse('<?php echo $categoriesJSON; ?>');
    // Retrieve and parse the sousCategories in JSON format passed from PHP
    const sousCategories = JSON.parse('<?php echo $sousCategories; ?>');
    // Retrieve the operations total by client passed from PHP
    const operationsTotalByClient = JSON.parse('<?php echo $operationsTotalByClientJSON; ?>');
    // Retrieve and parse the operations in JSON format passed from PHP
    const operationsJSON = operationsTotalByClient.filter(operation => operation.compte_id === selectedAccount || operation.compte_destinataire_id === selectedAccount);
    // Retrieve the mothly gains passed from PHP
    const totalActualMonthGains = '<?php echo $totalActualMonthGains; ?>';
    const totalLastMonthGains = '<?php echo $totalLastMonthGains; ?>';
    // Retrieve the mothly expenses passed from PHP
    const totalActualMonthDepenses = '<?php echo $totalActualMonthDepenses; ?>';
    const totalLastMonthDepenses = '<?php echo $totalLastMonthDepenses; ?>';
    // Retrieve the mothly saivings passed from PHP
    const totalActualMonthSavings = '<?php echo $totalActualMonthSavings; ?>';
    const totalLastMonthSavings = '<?php echo $totalLastMonthSavings; ?>';
    // Retrieve the mothly investments passed from PHP
    const totalActualMonthInvestments = '<?php echo $totalActualMonthInvestments; ?>';
    const totalLastMonthInvestments = '<?php echo $totalLastMonthInvestments; ?>';  
</script>